// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("timeseriesanomaly")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/processor/timeseriesanomalyprocessor"
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
